### ISSUE TITLE
Upload your song into the web browser via drag and drop

### ISSUE THREAD

**Issue by LtBackup** [LtBackup/Visualizer#17]
## DOD:
-[] Space exists for you to drag and drop 
-[] Space vanishes once file is uploaded
-[] Console.log 'upload was successful'

**Comment by cybernetck** [comment]
Made progress on this - I am able to get an MP3 file unto the page and log that it has been loaded; in testing/mattPullAudio.html <img width="1207" alt="screen shot 2018-03-08 at 10 54 53 am" src="https://user-images.githubusercontent.com/18689824/37164247-6173e998-22bf-11e8-90d3-9066a10eda92.png"> I drag and drop a file from my local computer, and play it.  I can also verify that the code is running, and not the built-in browser function for playing MP3s.

**Comment by cybernetck** [comment]
closes 17

**Comment by cybernetck** [comment]
DOD conditions met per consultation with @LtBackup. I will create a related issue to stop the song/visualization playing if another song is dropped in.
